### ISSUE TITLE
openssl error building openwebrtc-gst-plugins for iOS

### ISSUE THREAD

**Issue by ninjudd** [nirbheek/cerbero#21]
I get the following error when running `./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc` with 2b6b7ae6f0d0382e02f081f7fd67e8948f324a2f:

```
[(31/33) openwebrtc-gst-plugins -> configure ]
...
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for SSL_library_init in -lssl... no
configure: error: You need OpenSSL for the build
Running command 'mkdir -p m4 && autoreconf -fiv'
Running command './configure --prefix /Users/justin/cerbero/dist/ios_universal --libdir /Users/justin/cerbero/dist/ios_universal/lib              --enable-shared             --enable-static             --disable-debug             --disable-static-plugins             --disable-android-plugins             --disable-osx-plugins             --disable-linux-plugins             --disable-colorspace-converter --disable-maintainer-mode  --disable-silent-rules  --disable-introspection  --host=arm-apple-darwin10 --disable-maintainer-mode  --disable-silent-rules  --disable-introspection  --host=arm-apple-darwin10'

***** Error running 'package' command:
Recipe 'openwebrtc-gst-plugins' failed at the build step 'configure'
```

**Comment by ninjudd** [comment]
I tried adding openssl to deps in `recipes/openwebrtc-gst-plugins.recipe`, but no luck.

**Comment by nirbheek** [comment]
Yes, this is a known issue, and needs https://github.com/EricssonResearch/openwebrtc-gst-plugins/pull/32 to be fixed. Let's keep this issue open in the meantime.

**Comment by nirbheek** [comment]
Should be fixed now, thanks for reporting!

**Comment by KerwinMa** [comment]
I still have the issue on mac 10.10.1:
checking for openssl/ssl.h... yes
checking for SSL_library_init in -lssl... no
configure: error: You need OpenSSL for the build
Running command 'mkdir -p m4 && autoreconf -fiv'
Running command './configure --prefix /Users/kerwin.ma/cerbero/dist/ios_universal --libdir /Users/kerwin.ma/cerbero/dist/ios_universal/lib              --enable-shared             --enable-static             --disable-debug             --disable-static-plugins             --disable-android-plugins             --disable-osx-plugins             --disable-linux-plugins             --disable-colorspace-converter --disable-maintainer-mode  --disable-silent-rules  --disable-introspection  --host=arm-apple-darwin10'

Recipe 'openwebrtc-gst-plugins' failed at the build step 'configure'

**Comment by nirbheek** [comment]
Oh, I forgot to add it to the -static recipe. I'll fix this in a bit.

**Comment by nirbheek** [comment]
Actually fixed now.
